version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "master branch dependencies"
    groups:
      dev-dependency:
        dependency-type: "development"
      production-dependencies:
        dependency-type: "production"

