name: Build check for pull request

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - '.devcontainer/**'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v3
      - name: Install, build, and upload your site output
        uses: withastro/action@v0
        
